---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbox
  namespace: box
  labels:
    app: testbox
  annotations:
    flux.weave.works/automated: "true"
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: testbox
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: testbox
    spec:
      containers:
      - name: testbox
        image: 156194757130.dkr.ecr.us-east-1.amazonaws.com/diegotest:2
        imagePullPolicy: IfNotPresent
